### PR TITLE
Downtime notes 2.2

### PR DESCRIPTION
**Pull request by MirahImage**
Hi, 

These are additional notes regarding expected Service Instance downtime. If you could cherry pick 80f73fa and 00e9869 (but not the TLS commit) back to previous branches, we would appreciate it. 

Best,
Mirah & @jimbo459

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks, will do!

**Comment by jncd** [comment]
Hi @MirahImage 
Should this PR also be cherry-picked _forward_ to master? Will Applying Changes cause restarting of all the VMs in Redis for Pivotal Platform v2.3, too?

**Comment by jncd** [comment]
I also noticed a reference to consul in this table in the [installing page](https://docs.pivotal.io/redis/2-1/installing.html#network-configuration). Should this change too? 
Screen Shot 2019-09-30 at 4 58 30 PM

**Comment by MirahImage** [comment]
Consul does not exist in Redis anymore and has not since at least 2.0, so the reason is certainly wrong. I believe it would still be accurate to state that communication is necessary for metrics.

**Pull request merged**
