### PR TITLE
Update index.html.md.erb

### PR DESCRIPTION
**Pull request by stanimirovn**
Fix multi-line syntax for DW migration.

Which other branches should this be merged with (if any)?

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks, @stanimirovn, I'll cherry-pick this change to the other live branches (where applicable). 

In future, please answer the `Which other branches should this be merged with (if any)?` question that appears when creating a PR (see the top comment).

**Comment by stanimirovn** [comment]
My apologies, I would need them to go with 2.3, 2.4 and 3.0 as part of the migration.

**Comment by RichardJJG** [comment]
> My apologies, I would need them to go with 2.3, 2.4 and 3.0 as part of the migration.

Not 3.1 as well? The master branch is for Redis v3.2

**Comment by stanimirovn** [comment]
Hi Richard, I see a few other things that I would like to be carried over to different branches from the master one. 

- In **Index.html** from **Master** to **2.3** - <%= partial vars.path_to_partials + '/redis/service-offerings', :locals => {:redis_name => vars.product_short } %>

- In troubleshoot-instances.html from **Master** to **2.4**, all 4 troubleshoot templates starting from line 99

Please let me know if I should do a PRs directly in those branches.

**Comment by RichardJJG** [comment]
Hi, @stanimirovn, please create the PRs -- I think that's the least confusing option here.

**Pull request merged**
