### PR TITLE
Fix structure of the upgrade doc to comform to best practices

### PR DESCRIPTION
**Pull request by jplebre**
- Move instructions off breaking change note into the upgrade steps
section

[#161589128](https://www.pivotaltracker.com/story/show/161589128)

@edwardecook

### CODE REVIEW

**Comment by jplebre** [comment]
@jncd Changed the breaking change notes as requested, let me know if you have any more comments for us on these changes

**Comment by snneji** [comment]
Thanks @jplebre

**Comment by jncd** [comment]
Hi @jplebre and @edwardecook 
Thanks for doing this. It's in a good place and easy to understand. 
I like having the note in the release notes too — one request, can we use the same note in both places? 
Let us know if they need to be different. We'll plan to rationalize and partialize so they're always the same. 
cc @snneji

**Comment by jplebre** [comment]
Hi @jncd sounds good to us to have the same note in both places. The more visibility the better as this is a reasonably big breaking change.

**Pull request merged**
