### PR TITLE
Release notes for Redis 3.3.2 release

### PR DESCRIPTION
**Pull request by apurvasaraiya**
Hi team,

This is a new release doc for v3.3.2.
Please do review the changes and let us know if you need further information.

Thanks,
Redis Tile Team

### CODE REVIEW

**Comment by apurvasaraiya** [comment]
@RichardJJG Can you please undo/revert the merge? We still need reviews from other folks on documentation update.

Thank you

**Comment by RichardJJG** [comment]
@apurvasaraiya, please close this PR now that you have https://github.com/pivotal-cf/docs-redis/pull/525/files

**Comment by apurvasaraiya** [comment]
@RichardJJG, It shows PR already in the closed state.

**Comment by RichardJJG** [comment]
@apurvasaraiya, okay, thanks, I think the merging just makes it look otherwise. No further action needed.

**Pull request merged**
