### PR TITLE
REDVM-455: adds ha related documentation 

### PR DESCRIPTION
**Pull request by apurvasaraiya**

### CODE REVIEW

**Comment by HenryBorys** [comment]
I'll wait to merge to give reviewers a chance for input.

**Review by ashrivastav13 — APPROVED** [review]

**Comment by HenryBorys** [comment]
@apurvasaraiya As I'm editing the new pages, I notice there is a link to images/enable-ha.png, but that image doesn't exist in the branch. Are you planning on adding that image soon? Also, you added an image, on-demand-ha-arch.png, but I don't see that placed anywhere in the docs. Do you plan on adding that in somewhere?

**Comment by apurvasaraiya** [comment]
@HenryBorys 

Screenshot 2024-05-03 at 5 07 05 PM

This is the image, I missed to upload. Do you want me to create a PR for that? Or you'll take care of adding the image?

**Comment by HenryBorys** [comment]
Hi @apurvasaraiya I just added your new image. Thanks! However, I'm still wondering about the image you did add that I don't see in the docs anywhere: on-demand-ha-arch.png  Do you have plans for using that image? I just want to be sure you didn't overlook adding it to a doc if you intended to. Thanks again.

**Pull request merged**
